/* THIS FILE WAS AUTOMATICALLY GENERATED BY mkmacros.rb! DO NOT EDIT IT DIRECTLY. */
#ifdef __DBL_MIN_EXP__
    /* __DBL_MIN_EXP__ => "(-1021)" */
    {"__DBL_MIN_EXP__", STRMAC(__DBL_MIN_EXP__)},
#endif


#ifdef __FLT32X_MAX_EXP__
    /* __FLT32X_MAX_EXP__ => "1024" */
    {"__FLT32X_MAX_EXP__", STRMAC(__FLT32X_MAX_EXP__)},
#endif


#ifdef __UINT_LEAST16_MAX__
    /* __UINT_LEAST16_MAX__ => "0xffff" */
    {"__UINT_LEAST16_MAX__", STRMAC(__UINT_LEAST16_MAX__)},
#endif


#ifdef __ATOMIC_ACQUIRE
    /* __ATOMIC_ACQUIRE => "2" */
    {"__ATOMIC_ACQUIRE", STRMAC(__ATOMIC_ACQUIRE)},
#endif


#ifdef __FLT128_MAX_10_EXP__
    /* __FLT128_MAX_10_EXP__ => "4932" */
    {"__FLT128_MAX_10_EXP__", STRMAC(__FLT128_MAX_10_EXP__)},
#endif


#ifdef __FLT_MIN__
    /* __FLT_MIN__ => "1.17549435082228750796873653722224568e-38F" */
    {"__FLT_MIN__", STRMAC(__FLT_MIN__)},
#endif


#ifdef __GCC_IEC_559_COMPLEX
    /* __GCC_IEC_559_COMPLEX => "2" */
    {"__GCC_IEC_559_COMPLEX", STRMAC(__GCC_IEC_559_COMPLEX)},
#endif


#ifdef __UINT_LEAST8_TYPE__
    /* __UINT_LEAST8_TYPE__ => "unsigned char" */
    {"__UINT_LEAST8_TYPE__", STRMAC(__UINT_LEAST8_TYPE__)},
#endif


#ifdef __SIZEOF_FLOAT80__
    /* __SIZEOF_FLOAT80__ => "16" */
    {"__SIZEOF_FLOAT80__", STRMAC(__SIZEOF_FLOAT80__)},
#endif


#ifdef __CHAR_BIT__
    /* __CHAR_BIT__ => "8" */
    {"__CHAR_BIT__", STRMAC(__CHAR_BIT__)},
#endif


#ifdef __UINT8_MAX__
    /* __UINT8_MAX__ => "0xff" */
    {"__UINT8_MAX__", STRMAC(__UINT8_MAX__)},
#endif


#ifdef __WINT_MAX__
    /* __WINT_MAX__ => "0xffffffffU" */
    {"__WINT_MAX__", STRMAC(__WINT_MAX__)},
#endif


#ifdef __FLT32_MIN_EXP__
    /* __FLT32_MIN_EXP__ => "(-125)" */
    {"__FLT32_MIN_EXP__", STRMAC(__FLT32_MIN_EXP__)},
#endif


#ifdef __ORDER_LITTLE_ENDIAN__
    /* __ORDER_LITTLE_ENDIAN__ => "1234" */
    {"__ORDER_LITTLE_ENDIAN__", STRMAC(__ORDER_LITTLE_ENDIAN__)},
#endif


#ifdef __SIZE_MAX__
    /* __SIZE_MAX__ => "0xffffffffffffffffUL" */
    {"__SIZE_MAX__", STRMAC(__SIZE_MAX__)},
#endif


#ifdef __WCHAR_MAX__
    /* __WCHAR_MAX__ => "0xffff" */
    {"__WCHAR_MAX__", STRMAC(__WCHAR_MAX__)},
#endif


#ifdef __GCC_HAVE_SYNC_COMPARE_AND_SWAP_1
    /* __GCC_HAVE_SYNC_COMPARE_AND_SWAP_1 => "1" */
    {"__GCC_HAVE_SYNC_COMPARE_AND_SWAP_1", STRMAC(__GCC_HAVE_SYNC_COMPARE_AND_SWAP_1)},
#endif


#ifdef __GCC_HAVE_SYNC_COMPARE_AND_SWAP_2
    /* __GCC_HAVE_SYNC_COMPARE_AND_SWAP_2 => "1" */
    {"__GCC_HAVE_SYNC_COMPARE_AND_SWAP_2", STRMAC(__GCC_HAVE_SYNC_COMPARE_AND_SWAP_2)},
#endif


#ifdef __GCC_HAVE_SYNC_COMPARE_AND_SWAP_4
    /* __GCC_HAVE_SYNC_COMPARE_AND_SWAP_4 => "1" */
    {"__GCC_HAVE_SYNC_COMPARE_AND_SWAP_4", STRMAC(__GCC_HAVE_SYNC_COMPARE_AND_SWAP_4)},
#endif


#ifdef __DBL_DENORM_MIN__
    /* __DBL_DENORM_MIN__ => "((double)4.94065645841246544176568792868221372e-324L)" */
    {"__DBL_DENORM_MIN__", STRMAC(__DBL_DENORM_MIN__)},
#endif


#ifdef __GCC_HAVE_SYNC_COMPARE_AND_SWAP_8
    /* __GCC_HAVE_SYNC_COMPARE_AND_SWAP_8 => "1" */
    {"__GCC_HAVE_SYNC_COMPARE_AND_SWAP_8", STRMAC(__GCC_HAVE_SYNC_COMPARE_AND_SWAP_8)},
#endif


#ifdef __GCC_ATOMIC_CHAR_LOCK_FREE
    /* __GCC_ATOMIC_CHAR_LOCK_FREE => "2" */
    {"__GCC_ATOMIC_CHAR_LOCK_FREE", STRMAC(__GCC_ATOMIC_CHAR_LOCK_FREE)},
#endif


#ifdef __GCC_IEC_559
    /* __GCC_IEC_559 => "2" */
    {"__GCC_IEC_559", STRMAC(__GCC_IEC_559)},
#endif


#ifdef __FLT32X_DECIMAL_DIG__
    /* __FLT32X_DECIMAL_DIG__ => "17" */
    {"__FLT32X_DECIMAL_DIG__", STRMAC(__FLT32X_DECIMAL_DIG__)},
#endif


#ifdef __FLT_EVAL_METHOD__
    /* __FLT_EVAL_METHOD__ => "0" */
    {"__FLT_EVAL_METHOD__", STRMAC(__FLT_EVAL_METHOD__)},
#endif


#ifdef __unix__
    /* __unix__ => "1" */
    {"__unix__", STRMAC(__unix__)},
#endif


#ifdef __FLT64_DECIMAL_DIG__
    /* __FLT64_DECIMAL_DIG__ => "17" */
    {"__FLT64_DECIMAL_DIG__", STRMAC(__FLT64_DECIMAL_DIG__)},
#endif


#ifdef __GCC_ATOMIC_CHAR32_T_LOCK_FREE
    /* __GCC_ATOMIC_CHAR32_T_LOCK_FREE => "2" */
    {"__GCC_ATOMIC_CHAR32_T_LOCK_FREE", STRMAC(__GCC_ATOMIC_CHAR32_T_LOCK_FREE)},
#endif


#ifdef __x86_64
    /* __x86_64 => "1" */
    {"__x86_64", STRMAC(__x86_64)},
#endif


#ifdef __UINT_FAST64_MAX__
    /* __UINT_FAST64_MAX__ => "0xffffffffffffffffUL" */
    {"__UINT_FAST64_MAX__", STRMAC(__UINT_FAST64_MAX__)},
#endif


#ifdef __SIG_ATOMIC_TYPE__
    /* __SIG_ATOMIC_TYPE__ => "int" */
    {"__SIG_ATOMIC_TYPE__", STRMAC(__SIG_ATOMIC_TYPE__)},
#endif


#ifdef __DBL_MIN_10_EXP__
    /* __DBL_MIN_10_EXP__ => "(-307)" */
    {"__DBL_MIN_10_EXP__", STRMAC(__DBL_MIN_10_EXP__)},
#endif


#ifdef __FINITE_MATH_ONLY__
    /* __FINITE_MATH_ONLY__ => "0" */
    {"__FINITE_MATH_ONLY__", STRMAC(__FINITE_MATH_ONLY__)},
#endif


#ifdef __GNUC_PATCHLEVEL__
    /* __GNUC_PATCHLEVEL__ => "0" */
    {"__GNUC_PATCHLEVEL__", STRMAC(__GNUC_PATCHLEVEL__)},
#endif


#ifdef __FLT32_HAS_DENORM__
    /* __FLT32_HAS_DENORM__ => "1" */
    {"__FLT32_HAS_DENORM__", STRMAC(__FLT32_HAS_DENORM__)},
#endif


#ifdef __UINT_FAST8_MAX__
    /* __UINT_FAST8_MAX__ => "0xff" */
    {"__UINT_FAST8_MAX__", STRMAC(__UINT_FAST8_MAX__)},
#endif


#ifdef _stdcall
    /* _stdcall => "__attribute__((__stdcall__))" */
    {"_stdcall", STRMAC(_stdcall)},
#endif


#ifdef __DEC64_MAX_EXP__
    /* __DEC64_MAX_EXP__ => "385" */
    {"__DEC64_MAX_EXP__", STRMAC(__DEC64_MAX_EXP__)},
#endif


#ifdef __INT_LEAST8_WIDTH__
    /* __INT_LEAST8_WIDTH__ => "8" */
    {"__INT_LEAST8_WIDTH__", STRMAC(__INT_LEAST8_WIDTH__)},
#endif


#ifdef __UINT_LEAST64_MAX__
    /* __UINT_LEAST64_MAX__ => "0xffffffffffffffffUL" */
    {"__UINT_LEAST64_MAX__", STRMAC(__UINT_LEAST64_MAX__)},
#endif


#ifdef __SHRT_MAX__
    /* __SHRT_MAX__ => "0x7fff" */
    {"__SHRT_MAX__", STRMAC(__SHRT_MAX__)},
#endif


#ifdef __LDBL_MAX__
    /* __LDBL_MAX__ => "1.18973149535723176502126385303097021e+4932L" */
    {"__LDBL_MAX__", STRMAC(__LDBL_MAX__)},
#endif


#ifdef __FLT64X_MAX_10_EXP__
    /* __FLT64X_MAX_10_EXP__ => "4932" */
    {"__FLT64X_MAX_10_EXP__", STRMAC(__FLT64X_MAX_10_EXP__)},
#endif


#ifdef __UINT_LEAST8_MAX__
    /* __UINT_LEAST8_MAX__ => "0xff" */
    {"__UINT_LEAST8_MAX__", STRMAC(__UINT_LEAST8_MAX__)},
#endif


#ifdef __GCC_ATOMIC_BOOL_LOCK_FREE
    /* __GCC_ATOMIC_BOOL_LOCK_FREE => "2" */
    {"__GCC_ATOMIC_BOOL_LOCK_FREE", STRMAC(__GCC_ATOMIC_BOOL_LOCK_FREE)},
#endif


#ifdef __FLT128_DENORM_MIN__
    /* __FLT128_DENORM_MIN__ => "6.47517511943802511092443895822764655e-4966F128" */
    {"__FLT128_DENORM_MIN__", STRMAC(__FLT128_DENORM_MIN__)},
#endif


#ifdef __UINTMAX_TYPE__
    /* __UINTMAX_TYPE__ => "long unsigned int" */
    {"__UINTMAX_TYPE__", STRMAC(__UINTMAX_TYPE__)},
#endif


#ifdef __DEC32_EPSILON__
    /* __DEC32_EPSILON__ => "1E-6DF" */
    {"__DEC32_EPSILON__", STRMAC(__DEC32_EPSILON__)},
#endif


#ifdef __FLT_EVAL_METHOD_TS_18661_3__
    /* __FLT_EVAL_METHOD_TS_18661_3__ => "0" */
    {"__FLT_EVAL_METHOD_TS_18661_3__", STRMAC(__FLT_EVAL_METHOD_TS_18661_3__)},
#endif


#ifdef __unix
    /* __unix => "1" */
    {"__unix", STRMAC(__unix)},
#endif


#ifdef __UINT32_MAX__
    /* __UINT32_MAX__ => "0xffffffffU" */
    {"__UINT32_MAX__", STRMAC(__UINT32_MAX__)},
#endif


#ifdef __LDBL_MAX_EXP__
    /* __LDBL_MAX_EXP__ => "16384" */
    {"__LDBL_MAX_EXP__", STRMAC(__LDBL_MAX_EXP__)},
#endif


#ifdef __FLT128_MIN_EXP__
    /* __FLT128_MIN_EXP__ => "(-16381)" */
    {"__FLT128_MIN_EXP__", STRMAC(__FLT128_MIN_EXP__)},
#endif


#ifdef __WINT_MIN__
    /* __WINT_MIN__ => "0U" */
    {"__WINT_MIN__", STRMAC(__WINT_MIN__)},
#endif


#ifdef __FLT128_MIN_10_EXP__
    /* __FLT128_MIN_10_EXP__ => "(-4931)" */
    {"__FLT128_MIN_10_EXP__", STRMAC(__FLT128_MIN_10_EXP__)},
#endif


#ifdef __INT_LEAST16_WIDTH__
    /* __INT_LEAST16_WIDTH__ => "16" */
    {"__INT_LEAST16_WIDTH__", STRMAC(__INT_LEAST16_WIDTH__)},
#endif


#ifdef __SCHAR_MAX__
    /* __SCHAR_MAX__ => "0x7f" */
    {"__SCHAR_MAX__", STRMAC(__SCHAR_MAX__)},
#endif


#ifdef __FLT128_MANT_DIG__
    /* __FLT128_MANT_DIG__ => "113" */
    {"__FLT128_MANT_DIG__", STRMAC(__FLT128_MANT_DIG__)},
#endif


#ifdef __WCHAR_MIN__
    /* __WCHAR_MIN__ => "0" */
    {"__WCHAR_MIN__", STRMAC(__WCHAR_MIN__)},
#endif


#ifdef __DBL_DIG__
    /* __DBL_DIG__ => "15" */
    {"__DBL_DIG__", STRMAC(__DBL_DIG__)},
#endif


#ifdef __GCC_ATOMIC_POINTER_LOCK_FREE
    /* __GCC_ATOMIC_POINTER_LOCK_FREE => "2" */
    {"__GCC_ATOMIC_POINTER_LOCK_FREE", STRMAC(__GCC_ATOMIC_POINTER_LOCK_FREE)},
#endif


#ifdef __FLT64X_MANT_DIG__
    /* __FLT64X_MANT_DIG__ => "64" */
    {"__FLT64X_MANT_DIG__", STRMAC(__FLT64X_MANT_DIG__)},
#endif


#ifdef __SIZEOF_INT__
    /* __SIZEOF_INT__ => "4" */
    {"__SIZEOF_INT__", STRMAC(__SIZEOF_INT__)},
#endif


#ifdef __SIZEOF_POINTER__
    /* __SIZEOF_POINTER__ => "8" */
    {"__SIZEOF_POINTER__", STRMAC(__SIZEOF_POINTER__)},
#endif


#ifdef __FLT64X_EPSILON__
    /* __FLT64X_EPSILON__ => "1.08420217248550443400745280086994171e-19F64x" */
    {"__FLT64X_EPSILON__", STRMAC(__FLT64X_EPSILON__)},
#endif


#ifdef __STDC_HOSTED__
    /* __STDC_HOSTED__ => "1" */
    {"__STDC_HOSTED__", STRMAC(__STDC_HOSTED__)},
#endif


#ifdef __LDBL_HAS_INFINITY__
    /* __LDBL_HAS_INFINITY__ => "1" */
    {"__LDBL_HAS_INFINITY__", STRMAC(__LDBL_HAS_INFINITY__)},
#endif


#ifdef __FLT32_DIG__
    /* __FLT32_DIG__ => "6" */
    {"__FLT32_DIG__", STRMAC(__FLT32_DIG__)},
#endif


#ifdef __FLT_EPSILON__
    /* __FLT_EPSILON__ => "1.19209289550781250000000000000000000e-7F" */
    {"__FLT_EPSILON__", STRMAC(__FLT_EPSILON__)},
#endif


#ifdef __SHRT_WIDTH__
    /* __SHRT_WIDTH__ => "16" */
    {"__SHRT_WIDTH__", STRMAC(__SHRT_WIDTH__)},
#endif


#ifdef __LDBL_MIN__
    /* __LDBL_MIN__ => "3.36210314311209350626267781732175260e-4932L" */
    {"__LDBL_MIN__", STRMAC(__LDBL_MIN__)},
#endif


#ifdef __STDC_UTF_16__
    /* __STDC_UTF_16__ => "1" */
    {"__STDC_UTF_16__", STRMAC(__STDC_UTF_16__)},
#endif


#ifdef __DEC32_MAX__
    /* __DEC32_MAX__ => "9.999999E96DF" */
    {"__DEC32_MAX__", STRMAC(__DEC32_MAX__)},
#endif


#ifdef __FLT64X_DENORM_MIN__
    /* __FLT64X_DENORM_MIN__ => "3.64519953188247460252840593361941982e-4951F64x" */
    {"__FLT64X_DENORM_MIN__", STRMAC(__FLT64X_DENORM_MIN__)},
#endif


#ifdef __FLT32X_HAS_INFINITY__
    /* __FLT32X_HAS_INFINITY__ => "1" */
    {"__FLT32X_HAS_INFINITY__", STRMAC(__FLT32X_HAS_INFINITY__)},
#endif


#ifdef __INT32_MAX__
    /* __INT32_MAX__ => "0x7fffffff" */
    {"__INT32_MAX__", STRMAC(__INT32_MAX__)},
#endif


#ifdef __INT_WIDTH__
    /* __INT_WIDTH__ => "32" */
    {"__INT_WIDTH__", STRMAC(__INT_WIDTH__)},
#endif


#ifdef __SIZEOF_LONG__
    /* __SIZEOF_LONG__ => "8" */
    {"__SIZEOF_LONG__", STRMAC(__SIZEOF_LONG__)},
#endif


#ifdef __PTRDIFF_WIDTH__
    /* __PTRDIFF_WIDTH__ => "64" */
    {"__PTRDIFF_WIDTH__", STRMAC(__PTRDIFF_WIDTH__)},
#endif


#ifdef __DECIMAL_DIG__
    /* __DECIMAL_DIG__ => "21" */
    {"__DECIMAL_DIG__", STRMAC(__DECIMAL_DIG__)},
#endif


#ifdef __FLT64_EPSILON__
    /* __FLT64_EPSILON__ => "2.22044604925031308084726333618164062e-16F64" */
    {"__FLT64_EPSILON__", STRMAC(__FLT64_EPSILON__)},
#endif


#ifdef __INTMAX_WIDTH__
    /* __INTMAX_WIDTH__ => "64" */
    {"__INTMAX_WIDTH__", STRMAC(__INTMAX_WIDTH__)},
#endif


#ifdef __FLT64X_MIN_10_EXP__
    /* __FLT64X_MIN_10_EXP__ => "(-4931)" */
    {"__FLT64X_MIN_10_EXP__", STRMAC(__FLT64X_MIN_10_EXP__)},
#endif


#ifdef __LDBL_HAS_QUIET_NAN__
    /* __LDBL_HAS_QUIET_NAN__ => "1" */
    {"__LDBL_HAS_QUIET_NAN__", STRMAC(__LDBL_HAS_QUIET_NAN__)},
#endif


#ifdef __FLT64_MANT_DIG__
    /* __FLT64_MANT_DIG__ => "53" */
    {"__FLT64_MANT_DIG__", STRMAC(__FLT64_MANT_DIG__)},
#endif


#ifdef __GNUC__
    /* __GNUC__ => "9" */
    {"__GNUC__", STRMAC(__GNUC__)},
#endif


#ifdef __MMX__
    /* __MMX__ => "1" */
    {"__MMX__", STRMAC(__MMX__)},
#endif


#ifdef __FLT_HAS_DENORM__
    /* __FLT_HAS_DENORM__ => "1" */
    {"__FLT_HAS_DENORM__", STRMAC(__FLT_HAS_DENORM__)},
#endif


#ifdef __SIZEOF_LONG_DOUBLE__
    /* __SIZEOF_LONG_DOUBLE__ => "16" */
    {"__SIZEOF_LONG_DOUBLE__", STRMAC(__SIZEOF_LONG_DOUBLE__)},
#endif


#ifdef __BIGGEST_ALIGNMENT__
    /* __BIGGEST_ALIGNMENT__ => "16" */
    {"__BIGGEST_ALIGNMENT__", STRMAC(__BIGGEST_ALIGNMENT__)},
#endif


#ifdef __FLT64_MAX_10_EXP__
    /* __FLT64_MAX_10_EXP__ => "308" */
    {"__FLT64_MAX_10_EXP__", STRMAC(__FLT64_MAX_10_EXP__)},
#endif


#ifdef __DBL_MAX__
    /* __DBL_MAX__ => "((double)1.79769313486231570814527423731704357e+308L)" */
    {"__DBL_MAX__", STRMAC(__DBL_MAX__)},
#endif


#ifdef _thiscall
    /* _thiscall => "__attribute__((__thiscall__))" */
    {"_thiscall", STRMAC(_thiscall)},
#endif


#ifdef __INT_FAST32_MAX__
    /* __INT_FAST32_MAX__ => "0x7fffffffffffffffL" */
    {"__INT_FAST32_MAX__", STRMAC(__INT_FAST32_MAX__)},
#endif


#ifdef __DBL_HAS_INFINITY__
    /* __DBL_HAS_INFINITY__ => "1" */
    {"__DBL_HAS_INFINITY__", STRMAC(__DBL_HAS_INFINITY__)},
#endif


#ifdef __HAVE_SPECULATION_SAFE_VALUE
    /* __HAVE_SPECULATION_SAFE_VALUE => "1" */
    {"__HAVE_SPECULATION_SAFE_VALUE", STRMAC(__HAVE_SPECULATION_SAFE_VALUE)},
#endif


#ifdef __DEC32_MIN_EXP__
    /* __DEC32_MIN_EXP__ => "(-94)" */
    {"__DEC32_MIN_EXP__", STRMAC(__DEC32_MIN_EXP__)},
#endif


#ifdef __INTPTR_WIDTH__
    /* __INTPTR_WIDTH__ => "64" */
    {"__INTPTR_WIDTH__", STRMAC(__INTPTR_WIDTH__)},
#endif


#ifdef __FLT32X_HAS_DENORM__
    /* __FLT32X_HAS_DENORM__ => "1" */
    {"__FLT32X_HAS_DENORM__", STRMAC(__FLT32X_HAS_DENORM__)},
#endif


#ifdef __INT_FAST16_TYPE__
    /* __INT_FAST16_TYPE__ => "long int" */
    {"__INT_FAST16_TYPE__", STRMAC(__INT_FAST16_TYPE__)},
#endif


#ifdef _fastcall
    /* _fastcall => "__attribute__((__fastcall__))" */
    {"_fastcall", STRMAC(_fastcall)},
#endif


#ifdef __LDBL_HAS_DENORM__
    /* __LDBL_HAS_DENORM__ => "1" */
    {"__LDBL_HAS_DENORM__", STRMAC(__LDBL_HAS_DENORM__)},
#endif


#ifdef __FLT128_HAS_INFINITY__
    /* __FLT128_HAS_INFINITY__ => "1" */
    {"__FLT128_HAS_INFINITY__", STRMAC(__FLT128_HAS_INFINITY__)},
#endif


#ifdef __DEC128_MAX__
    /* __DEC128_MAX__ => "9.999999999999999999999999999999999E6144DL" */
    {"__DEC128_MAX__", STRMAC(__DEC128_MAX__)},
#endif


#ifdef __INT_LEAST32_MAX__
    /* __INT_LEAST32_MAX__ => "0x7fffffff" */
    {"__INT_LEAST32_MAX__", STRMAC(__INT_LEAST32_MAX__)},
#endif


#ifdef __DEC32_MIN__
    /* __DEC32_MIN__ => "1E-95DF" */
    {"__DEC32_MIN__", STRMAC(__DEC32_MIN__)},
#endif


#ifdef __DBL_MAX_EXP__
    /* __DBL_MAX_EXP__ => "1024" */
    {"__DBL_MAX_EXP__", STRMAC(__DBL_MAX_EXP__)},
#endif


#ifdef __WCHAR_WIDTH__
    /* __WCHAR_WIDTH__ => "16" */
    {"__WCHAR_WIDTH__", STRMAC(__WCHAR_WIDTH__)},
#endif


#ifdef __FLT32_MAX__
    /* __FLT32_MAX__ => "3.40282346638528859811704183484516925e+38F32" */
    {"__FLT32_MAX__", STRMAC(__FLT32_MAX__)},
#endif


#ifdef __DEC128_EPSILON__
    /* __DEC128_EPSILON__ => "1E-33DL" */
    {"__DEC128_EPSILON__", STRMAC(__DEC128_EPSILON__)},
#endif


#ifdef __SSE2_MATH__
    /* __SSE2_MATH__ => "1" */
    {"__SSE2_MATH__", STRMAC(__SSE2_MATH__)},
#endif


#ifdef __ATOMIC_HLE_RELEASE
    /* __ATOMIC_HLE_RELEASE => "131072" */
    {"__ATOMIC_HLE_RELEASE", STRMAC(__ATOMIC_HLE_RELEASE)},
#endif


#ifdef __PTRDIFF_MAX__
    /* __PTRDIFF_MAX__ => "0x7fffffffffffffffL" */
    {"__PTRDIFF_MAX__", STRMAC(__PTRDIFF_MAX__)},
#endif


#ifdef __amd64
    /* __amd64 => "1" */
    {"__amd64", STRMAC(__amd64)},
#endif


#ifdef __ATOMIC_HLE_ACQUIRE
    /* __ATOMIC_HLE_ACQUIRE => "65536" */
    {"__ATOMIC_HLE_ACQUIRE", STRMAC(__ATOMIC_HLE_ACQUIRE)},
#endif


#ifdef __FLT32_HAS_QUIET_NAN__
    /* __FLT32_HAS_QUIET_NAN__ => "1" */
    {"__FLT32_HAS_QUIET_NAN__", STRMAC(__FLT32_HAS_QUIET_NAN__)},
#endif


#ifdef __LONG_LONG_MAX__
    /* __LONG_LONG_MAX__ => "0x7fffffffffffffffLL" */
    {"__LONG_LONG_MAX__", STRMAC(__LONG_LONG_MAX__)},
#endif


#ifdef __SIZEOF_SIZE_T__
    /* __SIZEOF_SIZE_T__ => "8" */
    {"__SIZEOF_SIZE_T__", STRMAC(__SIZEOF_SIZE_T__)},
#endif


#ifdef __FLT64X_MIN_EXP__
    /* __FLT64X_MIN_EXP__ => "(-16381)" */
    {"__FLT64X_MIN_EXP__", STRMAC(__FLT64X_MIN_EXP__)},
#endif


#ifdef __SIZEOF_WINT_T__
    /* __SIZEOF_WINT_T__ => "4" */
    {"__SIZEOF_WINT_T__", STRMAC(__SIZEOF_WINT_T__)},
#endif


#ifdef __LONG_LONG_WIDTH__
    /* __LONG_LONG_WIDTH__ => "64" */
    {"__LONG_LONG_WIDTH__", STRMAC(__LONG_LONG_WIDTH__)},
#endif


#ifdef __FLT32_MAX_EXP__
    /* __FLT32_MAX_EXP__ => "128" */
    {"__FLT32_MAX_EXP__", STRMAC(__FLT32_MAX_EXP__)},
#endif


#ifdef __GXX_ABI_VERSION
    /* __GXX_ABI_VERSION => "1013" */
    {"__GXX_ABI_VERSION", STRMAC(__GXX_ABI_VERSION)},
#endif


#ifdef __FLT_MIN_EXP__
    /* __FLT_MIN_EXP__ => "(-125)" */
    {"__FLT_MIN_EXP__", STRMAC(__FLT_MIN_EXP__)},
#endif


#ifdef __FLT64X_HAS_QUIET_NAN__
    /* __FLT64X_HAS_QUIET_NAN__ => "1" */
    {"__FLT64X_HAS_QUIET_NAN__", STRMAC(__FLT64X_HAS_QUIET_NAN__)},
#endif


#ifdef __INT_FAST64_TYPE__
    /* __INT_FAST64_TYPE__ => "long int" */
    {"__INT_FAST64_TYPE__", STRMAC(__INT_FAST64_TYPE__)},
#endif


#ifdef __FLT64_DENORM_MIN__
    /* __FLT64_DENORM_MIN__ => "4.94065645841246544176568792868221372e-324F64" */
    {"__FLT64_DENORM_MIN__", STRMAC(__FLT64_DENORM_MIN__)},
#endif


#ifdef __DBL_MIN__
    /* __DBL_MIN__ => "((double)2.22507385850720138309023271733240406e-308L)" */
    {"__DBL_MIN__", STRMAC(__DBL_MIN__)},
#endif


#ifdef __LP64__
    /* __LP64__ => "1" */
    {"__LP64__", STRMAC(__LP64__)},
#endif


#ifdef __FLT32X_EPSILON__
    /* __FLT32X_EPSILON__ => "2.22044604925031308084726333618164062e-16F32x" */
    {"__FLT32X_EPSILON__", STRMAC(__FLT32X_EPSILON__)},
#endif


#ifdef __DECIMAL_BID_FORMAT__
    /* __DECIMAL_BID_FORMAT__ => "1" */
    {"__DECIMAL_BID_FORMAT__", STRMAC(__DECIMAL_BID_FORMAT__)},
#endif


#ifdef __FLT64_MIN_EXP__
    /* __FLT64_MIN_EXP__ => "(-1021)" */
    {"__FLT64_MIN_EXP__", STRMAC(__FLT64_MIN_EXP__)},
#endif


#ifdef __GXX_TYPEINFO_EQUALITY_INLINE
    /* __GXX_TYPEINFO_EQUALITY_INLINE => "0" */
    {"__GXX_TYPEINFO_EQUALITY_INLINE", STRMAC(__GXX_TYPEINFO_EQUALITY_INLINE)},
#endif


#ifdef __FLT64_MIN_10_EXP__
    /* __FLT64_MIN_10_EXP__ => "(-307)" */
    {"__FLT64_MIN_10_EXP__", STRMAC(__FLT64_MIN_10_EXP__)},
#endif


#ifdef __FLT64X_DECIMAL_DIG__
    /* __FLT64X_DECIMAL_DIG__ => "21" */
    {"__FLT64X_DECIMAL_DIG__", STRMAC(__FLT64X_DECIMAL_DIG__)},
#endif


#ifdef __DEC128_MIN__
    /* __DEC128_MIN__ => "1E-6143DL" */
    {"__DEC128_MIN__", STRMAC(__DEC128_MIN__)},
#endif


#ifdef __UINT16_MAX__
    /* __UINT16_MAX__ => "0xffff" */
    {"__UINT16_MAX__", STRMAC(__UINT16_MAX__)},
#endif


#ifdef __DBL_HAS_DENORM__
    /* __DBL_HAS_DENORM__ => "1" */
    {"__DBL_HAS_DENORM__", STRMAC(__DBL_HAS_DENORM__)},
#endif


#ifdef __FLT32_MIN__
    /* __FLT32_MIN__ => "1.17549435082228750796873653722224568e-38F32" */
    {"__FLT32_MIN__", STRMAC(__FLT32_MIN__)},
#endif


#ifdef __UINT8_TYPE__
    /* __UINT8_TYPE__ => "unsigned char" */
    {"__UINT8_TYPE__", STRMAC(__UINT8_TYPE__)},
#endif


#ifdef __NO_INLINE__
    /* __NO_INLINE__ => "1" */
    {"__NO_INLINE__", STRMAC(__NO_INLINE__)},
#endif


#ifdef __FLT_MANT_DIG__
    /* __FLT_MANT_DIG__ => "24" */
    {"__FLT_MANT_DIG__", STRMAC(__FLT_MANT_DIG__)},
#endif


#ifdef __LDBL_DECIMAL_DIG__
    /* __LDBL_DECIMAL_DIG__ => "21" */
    {"__LDBL_DECIMAL_DIG__", STRMAC(__LDBL_DECIMAL_DIG__)},
#endif


#ifdef __VERSION__
    /* __VERSION__ => "\"9.3.0\"" */
    {"__VERSION__", STRMAC(__VERSION__)},
#endif


#ifdef __GCC_ATOMIC_INT_LOCK_FREE
    /* __GCC_ATOMIC_INT_LOCK_FREE => "2" */
    {"__GCC_ATOMIC_INT_LOCK_FREE", STRMAC(__GCC_ATOMIC_INT_LOCK_FREE)},
#endif


#ifdef __FLT128_MAX_EXP__
    /* __FLT128_MAX_EXP__ => "16384" */
    {"__FLT128_MAX_EXP__", STRMAC(__FLT128_MAX_EXP__)},
#endif


#ifdef __FLT32_MANT_DIG__
    /* __FLT32_MANT_DIG__ => "24" */
    {"__FLT32_MANT_DIG__", STRMAC(__FLT32_MANT_DIG__)},
#endif


#ifdef __FLOAT_WORD_ORDER__
    /* __FLOAT_WORD_ORDER__ => "__ORDER_LITTLE_ENDIAN__" */
    {"__FLOAT_WORD_ORDER__", STRMAC(__FLOAT_WORD_ORDER__)},
#endif


#ifdef __FLT128_HAS_DENORM__
    /* __FLT128_HAS_DENORM__ => "1" */
    {"__FLT128_HAS_DENORM__", STRMAC(__FLT128_HAS_DENORM__)},
#endif


#ifdef __FLT128_DIG__
    /* __FLT128_DIG__ => "33" */
    {"__FLT128_DIG__", STRMAC(__FLT128_DIG__)},
#endif


#ifdef __SCHAR_WIDTH__
    /* __SCHAR_WIDTH__ => "8" */
    {"__SCHAR_WIDTH__", STRMAC(__SCHAR_WIDTH__)},
#endif


#ifdef __DEC64_EPSILON__
    /* __DEC64_EPSILON__ => "1E-15DD" */
    {"__DEC64_EPSILON__", STRMAC(__DEC64_EPSILON__)},
#endif


#ifdef __ORDER_PDP_ENDIAN__
    /* __ORDER_PDP_ENDIAN__ => "3412" */
    {"__ORDER_PDP_ENDIAN__", STRMAC(__ORDER_PDP_ENDIAN__)},
#endif


#ifdef __DEC128_MIN_EXP__
    /* __DEC128_MIN_EXP__ => "(-6142)" */
    {"__DEC128_MIN_EXP__", STRMAC(__DEC128_MIN_EXP__)},
#endif


#ifdef __FLT32_MAX_10_EXP__
    /* __FLT32_MAX_10_EXP__ => "38" */
    {"__FLT32_MAX_10_EXP__", STRMAC(__FLT32_MAX_10_EXP__)},
#endif


#ifdef __INT_FAST32_TYPE__
    /* __INT_FAST32_TYPE__ => "long int" */
    {"__INT_FAST32_TYPE__", STRMAC(__INT_FAST32_TYPE__)},
#endif


#ifdef __UINT_LEAST16_TYPE__
    /* __UINT_LEAST16_TYPE__ => "short unsigned int" */
    {"__UINT_LEAST16_TYPE__", STRMAC(__UINT_LEAST16_TYPE__)},
#endif


#ifdef __FLT64X_HAS_INFINITY__
    /* __FLT64X_HAS_INFINITY__ => "1" */
    {"__FLT64X_HAS_INFINITY__", STRMAC(__FLT64X_HAS_INFINITY__)},
#endif


#ifdef unix
    /* unix => "1" */
    {"unix", STRMAC(unix)},
#endif


#ifdef __INT16_MAX__
    /* __INT16_MAX__ => "0x7fff" */
    {"__INT16_MAX__", STRMAC(__INT16_MAX__)},
#endif


#ifdef __SIZE_TYPE__
    /* __SIZE_TYPE__ => "long unsigned int" */
    {"__SIZE_TYPE__", STRMAC(__SIZE_TYPE__)},
#endif


#ifdef __UINT64_MAX__
    /* __UINT64_MAX__ => "0xffffffffffffffffUL" */
    {"__UINT64_MAX__", STRMAC(__UINT64_MAX__)},
#endif


#ifdef __FLT64X_DIG__
    /* __FLT64X_DIG__ => "18" */
    {"__FLT64X_DIG__", STRMAC(__FLT64X_DIG__)},
#endif


#ifdef __INT8_TYPE__
    /* __INT8_TYPE__ => "signed char" */
    {"__INT8_TYPE__", STRMAC(__INT8_TYPE__)},
#endif


#ifdef __GCC_ASM_FLAG_OUTPUTS__
    /* __GCC_ASM_FLAG_OUTPUTS__ => "1" */
    {"__GCC_ASM_FLAG_OUTPUTS__", STRMAC(__GCC_ASM_FLAG_OUTPUTS__)},
#endif


#ifdef __FLT_RADIX__
    /* __FLT_RADIX__ => "2" */
    {"__FLT_RADIX__", STRMAC(__FLT_RADIX__)},
#endif


#ifdef __INT_LEAST16_TYPE__
    /* __INT_LEAST16_TYPE__ => "short int" */
    {"__INT_LEAST16_TYPE__", STRMAC(__INT_LEAST16_TYPE__)},
#endif


#ifdef __LDBL_EPSILON__
    /* __LDBL_EPSILON__ => "1.08420217248550443400745280086994171e-19L" */
    {"__LDBL_EPSILON__", STRMAC(__LDBL_EPSILON__)},
#endif


#ifdef __SSE_MATH__
    /* __SSE_MATH__ => "1" */
    {"__SSE_MATH__", STRMAC(__SSE_MATH__)},
#endif


#ifdef __k8
    /* __k8 => "1" */
    {"__k8", STRMAC(__k8)},
#endif


#ifdef __SEH__
    /* __SEH__ => "1" */
    {"__SEH__", STRMAC(__SEH__)},
#endif


#ifdef __SIG_ATOMIC_MAX__
    /* __SIG_ATOMIC_MAX__ => "0x7fffffff" */
    {"__SIG_ATOMIC_MAX__", STRMAC(__SIG_ATOMIC_MAX__)},
#endif


#ifdef __GCC_ATOMIC_WCHAR_T_LOCK_FREE
    /* __GCC_ATOMIC_WCHAR_T_LOCK_FREE => "2" */
    {"__GCC_ATOMIC_WCHAR_T_LOCK_FREE", STRMAC(__GCC_ATOMIC_WCHAR_T_LOCK_FREE)},
#endif


#ifdef __SIZEOF_PTRDIFF_T__
    /* __SIZEOF_PTRDIFF_T__ => "8" */
    {"__SIZEOF_PTRDIFF_T__", STRMAC(__SIZEOF_PTRDIFF_T__)},
#endif


#ifdef __FLT32X_MANT_DIG__
    /* __FLT32X_MANT_DIG__ => "53" */
    {"__FLT32X_MANT_DIG__", STRMAC(__FLT32X_MANT_DIG__)},
#endif


#ifdef __CYGWIN__
    /* __CYGWIN__ => "1" */
    {"__CYGWIN__", STRMAC(__CYGWIN__)},
#endif


#ifdef __x86_64__
    /* __x86_64__ => "1" */
    {"__x86_64__", STRMAC(__x86_64__)},
#endif


#ifdef __FLT32X_MIN_EXP__
    /* __FLT32X_MIN_EXP__ => "(-1021)" */
    {"__FLT32X_MIN_EXP__", STRMAC(__FLT32X_MIN_EXP__)},
#endif


#ifdef __DEC32_SUBNORMAL_MIN__
    /* __DEC32_SUBNORMAL_MIN__ => "0.000001E-95DF" */
    {"__DEC32_SUBNORMAL_MIN__", STRMAC(__DEC32_SUBNORMAL_MIN__)},
#endif


#ifdef __INT_FAST16_MAX__
    /* __INT_FAST16_MAX__ => "0x7fffffffffffffffL" */
    {"__INT_FAST16_MAX__", STRMAC(__INT_FAST16_MAX__)},
#endif


#ifdef __FLT64_DIG__
    /* __FLT64_DIG__ => "15" */
    {"__FLT64_DIG__", STRMAC(__FLT64_DIG__)},
#endif


#ifdef __UINT_FAST32_MAX__
    /* __UINT_FAST32_MAX__ => "0xffffffffffffffffUL" */
    {"__UINT_FAST32_MAX__", STRMAC(__UINT_FAST32_MAX__)},
#endif


#ifdef __UINT_LEAST64_TYPE__
    /* __UINT_LEAST64_TYPE__ => "long unsigned int" */
    {"__UINT_LEAST64_TYPE__", STRMAC(__UINT_LEAST64_TYPE__)},
#endif


#ifdef __FLT_HAS_QUIET_NAN__
    /* __FLT_HAS_QUIET_NAN__ => "1" */
    {"__FLT_HAS_QUIET_NAN__", STRMAC(__FLT_HAS_QUIET_NAN__)},
#endif


#ifdef __FLT_MAX_10_EXP__
    /* __FLT_MAX_10_EXP__ => "38" */
    {"__FLT_MAX_10_EXP__", STRMAC(__FLT_MAX_10_EXP__)},
#endif


#ifdef __LONG_MAX__
    /* __LONG_MAX__ => "0x7fffffffffffffffL" */
    {"__LONG_MAX__", STRMAC(__LONG_MAX__)},
#endif


#ifdef __FLT64X_HAS_DENORM__
    /* __FLT64X_HAS_DENORM__ => "1" */
    {"__FLT64X_HAS_DENORM__", STRMAC(__FLT64X_HAS_DENORM__)},
#endif


#ifdef __DEC128_SUBNORMAL_MIN__
    /* __DEC128_SUBNORMAL_MIN__ => "0.000000000000000000000000000000001E-6143DL" */
    {"__DEC128_SUBNORMAL_MIN__", STRMAC(__DEC128_SUBNORMAL_MIN__)},
#endif


#ifdef __FLT_HAS_INFINITY__
    /* __FLT_HAS_INFINITY__ => "1" */
    {"__FLT_HAS_INFINITY__", STRMAC(__FLT_HAS_INFINITY__)},
#endif


#ifdef __UINT_FAST16_TYPE__
    /* __UINT_FAST16_TYPE__ => "long unsigned int" */
    {"__UINT_FAST16_TYPE__", STRMAC(__UINT_FAST16_TYPE__)},
#endif


#ifdef __DEC64_MAX__
    /* __DEC64_MAX__ => "9.999999999999999E384DD" */
    {"__DEC64_MAX__", STRMAC(__DEC64_MAX__)},
#endif


#ifdef __INT_FAST32_WIDTH__
    /* __INT_FAST32_WIDTH__ => "64" */
    {"__INT_FAST32_WIDTH__", STRMAC(__INT_FAST32_WIDTH__)},
#endif


#ifdef __CHAR16_TYPE__
    /* __CHAR16_TYPE__ => "short unsigned int" */
    {"__CHAR16_TYPE__", STRMAC(__CHAR16_TYPE__)},
#endif


#ifdef __PRAGMA_REDEFINE_EXTNAME
    /* __PRAGMA_REDEFINE_EXTNAME => "1" */
    {"__PRAGMA_REDEFINE_EXTNAME", STRMAC(__PRAGMA_REDEFINE_EXTNAME)},
#endif


#ifdef __SIZE_WIDTH__
    /* __SIZE_WIDTH__ => "64" */
    {"__SIZE_WIDTH__", STRMAC(__SIZE_WIDTH__)},
#endif


#ifdef __SEG_FS
    /* __SEG_FS => "1" */
    {"__SEG_FS", STRMAC(__SEG_FS)},
#endif


#ifdef __INT_LEAST16_MAX__
    /* __INT_LEAST16_MAX__ => "0x7fff" */
    {"__INT_LEAST16_MAX__", STRMAC(__INT_LEAST16_MAX__)},
#endif


#ifdef __DEC64_MANT_DIG__
    /* __DEC64_MANT_DIG__ => "16" */
    {"__DEC64_MANT_DIG__", STRMAC(__DEC64_MANT_DIG__)},
#endif


#ifdef __INT64_MAX__
    /* __INT64_MAX__ => "0x7fffffffffffffffL" */
    {"__INT64_MAX__", STRMAC(__INT64_MAX__)},
#endif


#ifdef __UINT_LEAST32_MAX__
    /* __UINT_LEAST32_MAX__ => "0xffffffffU" */
    {"__UINT_LEAST32_MAX__", STRMAC(__UINT_LEAST32_MAX__)},
#endif


#ifdef __SEG_GS
    /* __SEG_GS => "1" */
    {"__SEG_GS", STRMAC(__SEG_GS)},
#endif


#ifdef __FLT32_DENORM_MIN__
    /* __FLT32_DENORM_MIN__ => "1.40129846432481707092372958328991613e-45F32" */
    {"__FLT32_DENORM_MIN__", STRMAC(__FLT32_DENORM_MIN__)},
#endif


#ifdef __GCC_ATOMIC_LONG_LOCK_FREE
    /* __GCC_ATOMIC_LONG_LOCK_FREE => "2" */
    {"__GCC_ATOMIC_LONG_LOCK_FREE", STRMAC(__GCC_ATOMIC_LONG_LOCK_FREE)},
#endif


#ifdef __SIG_ATOMIC_WIDTH__
    /* __SIG_ATOMIC_WIDTH__ => "32" */
    {"__SIG_ATOMIC_WIDTH__", STRMAC(__SIG_ATOMIC_WIDTH__)},
#endif


#ifdef __INT_LEAST64_TYPE__
    /* __INT_LEAST64_TYPE__ => "long int" */
    {"__INT_LEAST64_TYPE__", STRMAC(__INT_LEAST64_TYPE__)},
#endif


#ifdef __INT16_TYPE__
    /* __INT16_TYPE__ => "short int" */
    {"__INT16_TYPE__", STRMAC(__INT16_TYPE__)},
#endif


#ifdef __INT_LEAST8_TYPE__
    /* __INT_LEAST8_TYPE__ => "signed char" */
    {"__INT_LEAST8_TYPE__", STRMAC(__INT_LEAST8_TYPE__)},
#endif


#ifdef __STDC_VERSION__
    /* __STDC_VERSION__ => "201710L" */
    {"__STDC_VERSION__", STRMAC(__STDC_VERSION__)},
#endif


#ifdef __DEC32_MAX_EXP__
    /* __DEC32_MAX_EXP__ => "97" */
    {"__DEC32_MAX_EXP__", STRMAC(__DEC32_MAX_EXP__)},
#endif


#ifdef __INT_FAST8_MAX__
    /* __INT_FAST8_MAX__ => "0x7f" */
    {"__INT_FAST8_MAX__", STRMAC(__INT_FAST8_MAX__)},
#endif


#ifdef __FLT128_MAX__
    /* __FLT128_MAX__ => "1.18973149535723176508575932662800702e+4932F128" */
    {"__FLT128_MAX__", STRMAC(__FLT128_MAX__)},
#endif


#ifdef __INTPTR_MAX__
    /* __INTPTR_MAX__ => "0x7fffffffffffffffL" */
    {"__INTPTR_MAX__", STRMAC(__INTPTR_MAX__)},
#endif


#ifdef __GXX_MERGED_TYPEINFO_NAMES
    /* __GXX_MERGED_TYPEINFO_NAMES => "0" */
    {"__GXX_MERGED_TYPEINFO_NAMES", STRMAC(__GXX_MERGED_TYPEINFO_NAMES)},
#endif


#ifdef __FLT64_HAS_QUIET_NAN__
    /* __FLT64_HAS_QUIET_NAN__ => "1" */
    {"__FLT64_HAS_QUIET_NAN__", STRMAC(__FLT64_HAS_QUIET_NAN__)},
#endif


#ifdef __stdcall
    /* __stdcall => "__attribute__((__stdcall__))" */
    {"__stdcall", STRMAC(__stdcall)},
#endif


#ifdef __FLT32_MIN_10_EXP__
    /* __FLT32_MIN_10_EXP__ => "(-37)" */
    {"__FLT32_MIN_10_EXP__", STRMAC(__FLT32_MIN_10_EXP__)},
#endif


#ifdef __SSE2__
    /* __SSE2__ => "1" */
    {"__SSE2__", STRMAC(__SSE2__)},
#endif


#ifdef __FLT32X_DIG__
    /* __FLT32X_DIG__ => "15" */
    {"__FLT32X_DIG__", STRMAC(__FLT32X_DIG__)},
#endif


#ifdef __LDBL_MANT_DIG__
    /* __LDBL_MANT_DIG__ => "64" */
    {"__LDBL_MANT_DIG__", STRMAC(__LDBL_MANT_DIG__)},
#endif


#ifdef __DBL_HAS_QUIET_NAN__
    /* __DBL_HAS_QUIET_NAN__ => "1" */
    {"__DBL_HAS_QUIET_NAN__", STRMAC(__DBL_HAS_QUIET_NAN__)},
#endif


#ifdef __FLT64_HAS_INFINITY__
    /* __FLT64_HAS_INFINITY__ => "1" */
    {"__FLT64_HAS_INFINITY__", STRMAC(__FLT64_HAS_INFINITY__)},
#endif


#ifdef __FLT64X_MAX__
    /* __FLT64X_MAX__ => "1.18973149535723176502126385303097021e+4932F64x" */
    {"__FLT64X_MAX__", STRMAC(__FLT64X_MAX__)},
#endif


#ifdef __SIG_ATOMIC_MIN__
    /* __SIG_ATOMIC_MIN__ => "(-__SIG_ATOMIC_MAX__ - 1)" */
    {"__SIG_ATOMIC_MIN__", STRMAC(__SIG_ATOMIC_MIN__)},
#endif


#ifdef __k8__
    /* __k8__ => "1" */
    {"__k8__", STRMAC(__k8__)},
#endif


#ifdef __INTPTR_TYPE__
    /* __INTPTR_TYPE__ => "long int" */
    {"__INTPTR_TYPE__", STRMAC(__INTPTR_TYPE__)},
#endif


#ifdef __UINT16_TYPE__
    /* __UINT16_TYPE__ => "short unsigned int" */
    {"__UINT16_TYPE__", STRMAC(__UINT16_TYPE__)},
#endif


#ifdef __WCHAR_TYPE__
    /* __WCHAR_TYPE__ => "short unsigned int" */
    {"__WCHAR_TYPE__", STRMAC(__WCHAR_TYPE__)},
#endif


#ifdef __SIZEOF_FLOAT__
    /* __SIZEOF_FLOAT__ => "4" */
    {"__SIZEOF_FLOAT__", STRMAC(__SIZEOF_FLOAT__)},
#endif


#ifdef __pic__
    /* __pic__ => "1" */
    {"__pic__", STRMAC(__pic__)},
#endif


#ifdef __UINTPTR_MAX__
    /* __UINTPTR_MAX__ => "0xffffffffffffffffUL" */
    {"__UINTPTR_MAX__", STRMAC(__UINTPTR_MAX__)},
#endif


#ifdef __INT_FAST64_WIDTH__
    /* __INT_FAST64_WIDTH__ => "64" */
    {"__INT_FAST64_WIDTH__", STRMAC(__INT_FAST64_WIDTH__)},
#endif


#ifdef __DEC64_MIN_EXP__
    /* __DEC64_MIN_EXP__ => "(-382)" */
    {"__DEC64_MIN_EXP__", STRMAC(__DEC64_MIN_EXP__)},
#endif


#ifdef __FLT32_DECIMAL_DIG__
    /* __FLT32_DECIMAL_DIG__ => "9" */
    {"__FLT32_DECIMAL_DIG__", STRMAC(__FLT32_DECIMAL_DIG__)},
#endif


#ifdef __INT_FAST64_MAX__
    /* __INT_FAST64_MAX__ => "0x7fffffffffffffffL" */
    {"__INT_FAST64_MAX__", STRMAC(__INT_FAST64_MAX__)},
#endif


#ifdef __GCC_ATOMIC_TEST_AND_SET_TRUEVAL
    /* __GCC_ATOMIC_TEST_AND_SET_TRUEVAL => "1" */
    {"__GCC_ATOMIC_TEST_AND_SET_TRUEVAL", STRMAC(__GCC_ATOMIC_TEST_AND_SET_TRUEVAL)},
#endif


#ifdef __FLT_DIG__
    /* __FLT_DIG__ => "6" */
    {"__FLT_DIG__", STRMAC(__FLT_DIG__)},
#endif


#ifdef __FLT32_HAS_INFINITY__
    /* __FLT32_HAS_INFINITY__ => "1" */
    {"__FLT32_HAS_INFINITY__", STRMAC(__FLT32_HAS_INFINITY__)},
#endif


#ifdef __FLT64X_MAX_EXP__
    /* __FLT64X_MAX_EXP__ => "16384" */
    {"__FLT64X_MAX_EXP__", STRMAC(__FLT64X_MAX_EXP__)},
#endif


#ifdef __UINT_FAST64_TYPE__
    /* __UINT_FAST64_TYPE__ => "long unsigned int" */
    {"__UINT_FAST64_TYPE__", STRMAC(__UINT_FAST64_TYPE__)},
#endif


#ifdef __INT_MAX__
    /* __INT_MAX__ => "0x7fffffff" */
    {"__INT_MAX__", STRMAC(__INT_MAX__)},
#endif


#ifdef __amd64__
    /* __amd64__ => "1" */
    {"__amd64__", STRMAC(__amd64__)},
#endif


#ifdef __code_model_medium__
    /* __code_model_medium__ => "1" */
    {"__code_model_medium__", STRMAC(__code_model_medium__)},
#endif


#ifdef __INT64_TYPE__
    /* __INT64_TYPE__ => "long int" */
    {"__INT64_TYPE__", STRMAC(__INT64_TYPE__)},
#endif


#ifdef __FLT_MAX_EXP__
    /* __FLT_MAX_EXP__ => "128" */
    {"__FLT_MAX_EXP__", STRMAC(__FLT_MAX_EXP__)},
#endif


#ifdef __ORDER_BIG_ENDIAN__
    /* __ORDER_BIG_ENDIAN__ => "4321" */
    {"__ORDER_BIG_ENDIAN__", STRMAC(__ORDER_BIG_ENDIAN__)},
#endif


#ifdef __DBL_MANT_DIG__
    /* __DBL_MANT_DIG__ => "53" */
    {"__DBL_MANT_DIG__", STRMAC(__DBL_MANT_DIG__)},
#endif


#ifdef __SIZEOF_FLOAT128__
    /* __SIZEOF_FLOAT128__ => "16" */
    {"__SIZEOF_FLOAT128__", STRMAC(__SIZEOF_FLOAT128__)},
#endif


#ifdef __INT_LEAST64_MAX__
    /* __INT_LEAST64_MAX__ => "0x7fffffffffffffffL" */
    {"__INT_LEAST64_MAX__", STRMAC(__INT_LEAST64_MAX__)},
#endif


#ifdef __GCC_ATOMIC_CHAR16_T_LOCK_FREE
    /* __GCC_ATOMIC_CHAR16_T_LOCK_FREE => "2" */
    {"__GCC_ATOMIC_CHAR16_T_LOCK_FREE", STRMAC(__GCC_ATOMIC_CHAR16_T_LOCK_FREE)},
#endif


#ifdef __DEC64_MIN__
    /* __DEC64_MIN__ => "1E-383DD" */
    {"__DEC64_MIN__", STRMAC(__DEC64_MIN__)},
#endif


#ifdef __WINT_TYPE__
    /* __WINT_TYPE__ => "unsigned int" */
    {"__WINT_TYPE__", STRMAC(__WINT_TYPE__)},
#endif


#ifdef __UINT_LEAST32_TYPE__
    /* __UINT_LEAST32_TYPE__ => "unsigned int" */
    {"__UINT_LEAST32_TYPE__", STRMAC(__UINT_LEAST32_TYPE__)},
#endif


#ifdef __SIZEOF_SHORT__
    /* __SIZEOF_SHORT__ => "2" */
    {"__SIZEOF_SHORT__", STRMAC(__SIZEOF_SHORT__)},
#endif


#ifdef __SSE__
    /* __SSE__ => "1" */
    {"__SSE__", STRMAC(__SSE__)},
#endif


#ifdef __LDBL_MIN_EXP__
    /* __LDBL_MIN_EXP__ => "(-16381)" */
    {"__LDBL_MIN_EXP__", STRMAC(__LDBL_MIN_EXP__)},
#endif


#ifdef __FLT64_MAX__
    /* __FLT64_MAX__ => "1.79769313486231570814527423731704357e+308F64" */
    {"__FLT64_MAX__", STRMAC(__FLT64_MAX__)},
#endif


#ifdef __WINT_WIDTH__
    /* __WINT_WIDTH__ => "32" */
    {"__WINT_WIDTH__", STRMAC(__WINT_WIDTH__)},
#endif


#ifdef __INT_LEAST8_MAX__
    /* __INT_LEAST8_MAX__ => "0x7f" */
    {"__INT_LEAST8_MAX__", STRMAC(__INT_LEAST8_MAX__)},
#endif


#ifdef __FLT32X_MAX_10_EXP__
    /* __FLT32X_MAX_10_EXP__ => "308" */
    {"__FLT32X_MAX_10_EXP__", STRMAC(__FLT32X_MAX_10_EXP__)},
#endif


#ifdef __SIZEOF_INT128__
    /* __SIZEOF_INT128__ => "16" */
    {"__SIZEOF_INT128__", STRMAC(__SIZEOF_INT128__)},
#endif


#ifdef __LDBL_MAX_10_EXP__
    /* __LDBL_MAX_10_EXP__ => "4932" */
    {"__LDBL_MAX_10_EXP__", STRMAC(__LDBL_MAX_10_EXP__)},
#endif


#ifdef __ATOMIC_RELAXED
    /* __ATOMIC_RELAXED => "0" */
    {"__ATOMIC_RELAXED", STRMAC(__ATOMIC_RELAXED)},
#endif


#ifdef __DBL_EPSILON__
    /* __DBL_EPSILON__ => "((double)2.22044604925031308084726333618164062e-16L)" */
    {"__DBL_EPSILON__", STRMAC(__DBL_EPSILON__)},
#endif


#ifdef __thiscall
    /* __thiscall => "__attribute__((__thiscall__))" */
    {"__thiscall", STRMAC(__thiscall)},
#endif


#ifdef __FLT128_MIN__
    /* __FLT128_MIN__ => "3.36210314311209350626267781732175260e-4932F128" */
    {"__FLT128_MIN__", STRMAC(__FLT128_MIN__)},
#endif


#ifdef _LP64
    /* _LP64 => "1" */
    {"_LP64", STRMAC(_LP64)},
#endif


#ifdef __FLT64_MAX_EXP__
    /* __FLT64_MAX_EXP__ => "1024" */
    {"__FLT64_MAX_EXP__", STRMAC(__FLT64_MAX_EXP__)},
#endif


#ifdef __INT_LEAST32_TYPE__
    /* __INT_LEAST32_TYPE__ => "int" */
    {"__INT_LEAST32_TYPE__", STRMAC(__INT_LEAST32_TYPE__)},
#endif


#ifdef __SIZEOF_WCHAR_T__
    /* __SIZEOF_WCHAR_T__ => "2" */
    {"__SIZEOF_WCHAR_T__", STRMAC(__SIZEOF_WCHAR_T__)},
#endif


#ifdef __UINT64_TYPE__
    /* __UINT64_TYPE__ => "long unsigned int" */
    {"__UINT64_TYPE__", STRMAC(__UINT64_TYPE__)},
#endif


#ifdef __FLT128_HAS_QUIET_NAN__
    /* __FLT128_HAS_QUIET_NAN__ => "1" */
    {"__FLT128_HAS_QUIET_NAN__", STRMAC(__FLT128_HAS_QUIET_NAN__)},
#endif


#ifdef __INT_FAST8_TYPE__
    /* __INT_FAST8_TYPE__ => "signed char" */
    {"__INT_FAST8_TYPE__", STRMAC(__INT_FAST8_TYPE__)},
#endif


#ifdef __fastcall
    /* __fastcall => "__attribute__((__fastcall__))" */
    {"__fastcall", STRMAC(__fastcall)},
#endif


#ifdef __FLT64X_MIN__
    /* __FLT64X_MIN__ => "3.36210314311209350626267781732175260e-4932F64x" */
    {"__FLT64X_MIN__", STRMAC(__FLT64X_MIN__)},
#endif


#ifdef __GNUC_STDC_INLINE__
    /* __GNUC_STDC_INLINE__ => "1" */
    {"__GNUC_STDC_INLINE__", STRMAC(__GNUC_STDC_INLINE__)},
#endif


#ifdef __FLT64_HAS_DENORM__
    /* __FLT64_HAS_DENORM__ => "1" */
    {"__FLT64_HAS_DENORM__", STRMAC(__FLT64_HAS_DENORM__)},
#endif


#ifdef __FLT32_EPSILON__
    /* __FLT32_EPSILON__ => "1.19209289550781250000000000000000000e-7F32" */
    {"__FLT32_EPSILON__", STRMAC(__FLT32_EPSILON__)},
#endif


#ifdef __DBL_DECIMAL_DIG__
    /* __DBL_DECIMAL_DIG__ => "17" */
    {"__DBL_DECIMAL_DIG__", STRMAC(__DBL_DECIMAL_DIG__)},
#endif


#ifdef __STDC_UTF_32__
    /* __STDC_UTF_32__ => "1" */
    {"__STDC_UTF_32__", STRMAC(__STDC_UTF_32__)},
#endif


#ifdef __INT_FAST8_WIDTH__
    /* __INT_FAST8_WIDTH__ => "8" */
    {"__INT_FAST8_WIDTH__", STRMAC(__INT_FAST8_WIDTH__)},
#endif


#ifdef __FXSR__
    /* __FXSR__ => "1" */
    {"__FXSR__", STRMAC(__FXSR__)},
#endif


#ifdef __DEC_EVAL_METHOD__
    /* __DEC_EVAL_METHOD__ => "2" */
    {"__DEC_EVAL_METHOD__", STRMAC(__DEC_EVAL_METHOD__)},
#endif


#ifdef __FLT32X_MAX__
    /* __FLT32X_MAX__ => "1.79769313486231570814527423731704357e+308F32x" */
    {"__FLT32X_MAX__", STRMAC(__FLT32X_MAX__)},
#endif


#ifdef __INTMAX_MAX__
    /* __INTMAX_MAX__ => "0x7fffffffffffffffL" */
    {"__INTMAX_MAX__", STRMAC(__INTMAX_MAX__)},
#endif


#ifdef __BYTE_ORDER__
    /* __BYTE_ORDER__ => "__ORDER_LITTLE_ENDIAN__" */
    {"__BYTE_ORDER__", STRMAC(__BYTE_ORDER__)},
#endif


#ifdef __FLT_DENORM_MIN__
    /* __FLT_DENORM_MIN__ => "1.40129846432481707092372958328991613e-45F" */
    {"__FLT_DENORM_MIN__", STRMAC(__FLT_DENORM_MIN__)},
#endif


#ifdef __INT8_MAX__
    /* __INT8_MAX__ => "0x7f" */
    {"__INT8_MAX__", STRMAC(__INT8_MAX__)},
#endif


#ifdef __LONG_WIDTH__
    /* __LONG_WIDTH__ => "64" */
    {"__LONG_WIDTH__", STRMAC(__LONG_WIDTH__)},
#endif


#ifdef __PIC__
    /* __PIC__ => "1" */
    {"__PIC__", STRMAC(__PIC__)},
#endif


#ifdef __UINT_FAST32_TYPE__
    /* __UINT_FAST32_TYPE__ => "long unsigned int" */
    {"__UINT_FAST32_TYPE__", STRMAC(__UINT_FAST32_TYPE__)},
#endif


#ifdef __CHAR32_TYPE__
    /* __CHAR32_TYPE__ => "unsigned int" */
    {"__CHAR32_TYPE__", STRMAC(__CHAR32_TYPE__)},
#endif


#ifdef __FLT_MAX__
    /* __FLT_MAX__ => "3.40282346638528859811704183484516925e+38F" */
    {"__FLT_MAX__", STRMAC(__FLT_MAX__)},
#endif


#ifdef __INT32_TYPE__
    /* __INT32_TYPE__ => "int" */
    {"__INT32_TYPE__", STRMAC(__INT32_TYPE__)},
#endif


#ifdef __SIZEOF_DOUBLE__
    /* __SIZEOF_DOUBLE__ => "8" */
    {"__SIZEOF_DOUBLE__", STRMAC(__SIZEOF_DOUBLE__)},
#endif


#ifdef __FLT_MIN_10_EXP__
    /* __FLT_MIN_10_EXP__ => "(-37)" */
    {"__FLT_MIN_10_EXP__", STRMAC(__FLT_MIN_10_EXP__)},
#endif


#ifdef __FLT64_MIN__
    /* __FLT64_MIN__ => "2.22507385850720138309023271733240406e-308F64" */
    {"__FLT64_MIN__", STRMAC(__FLT64_MIN__)},
#endif


#ifdef __INT_LEAST32_WIDTH__
    /* __INT_LEAST32_WIDTH__ => "32" */
    {"__INT_LEAST32_WIDTH__", STRMAC(__INT_LEAST32_WIDTH__)},
#endif


#ifdef __INTMAX_TYPE__
    /* __INTMAX_TYPE__ => "long int" */
    {"__INTMAX_TYPE__", STRMAC(__INTMAX_TYPE__)},
#endif


#ifdef __DEC128_MAX_EXP__
    /* __DEC128_MAX_EXP__ => "6145" */
    {"__DEC128_MAX_EXP__", STRMAC(__DEC128_MAX_EXP__)},
#endif


#ifdef __FLT32X_HAS_QUIET_NAN__
    /* __FLT32X_HAS_QUIET_NAN__ => "1" */
    {"__FLT32X_HAS_QUIET_NAN__", STRMAC(__FLT32X_HAS_QUIET_NAN__)},
#endif


#ifdef __ATOMIC_CONSUME
    /* __ATOMIC_CONSUME => "1" */
    {"__ATOMIC_CONSUME", STRMAC(__ATOMIC_CONSUME)},
#endif


#ifdef __GNUC_MINOR__
    /* __GNUC_MINOR__ => "3" */
    {"__GNUC_MINOR__", STRMAC(__GNUC_MINOR__)},
#endif


#ifdef __INT_FAST16_WIDTH__
    /* __INT_FAST16_WIDTH__ => "64" */
    {"__INT_FAST16_WIDTH__", STRMAC(__INT_FAST16_WIDTH__)},
#endif


#ifdef __UINTMAX_MAX__
    /* __UINTMAX_MAX__ => "0xffffffffffffffffUL" */
    {"__UINTMAX_MAX__", STRMAC(__UINTMAX_MAX__)},
#endif


#ifdef __DEC32_MANT_DIG__
    /* __DEC32_MANT_DIG__ => "7" */
    {"__DEC32_MANT_DIG__", STRMAC(__DEC32_MANT_DIG__)},
#endif


#ifdef __FLT32X_DENORM_MIN__
    /* __FLT32X_DENORM_MIN__ => "4.94065645841246544176568792868221372e-324F32x" */
    {"__FLT32X_DENORM_MIN__", STRMAC(__FLT32X_DENORM_MIN__)},
#endif


#ifdef __DBL_MAX_10_EXP__
    /* __DBL_MAX_10_EXP__ => "308" */
    {"__DBL_MAX_10_EXP__", STRMAC(__DBL_MAX_10_EXP__)},
#endif


#ifdef __LDBL_DENORM_MIN__
    /* __LDBL_DENORM_MIN__ => "3.64519953188247460252840593361941982e-4951L" */
    {"__LDBL_DENORM_MIN__", STRMAC(__LDBL_DENORM_MIN__)},
#endif


#ifdef __STDC__
    /* __STDC__ => "1" */
    {"__STDC__", STRMAC(__STDC__)},
#endif


#ifdef __PTRDIFF_TYPE__
    /* __PTRDIFF_TYPE__ => "long int" */
    {"__PTRDIFF_TYPE__", STRMAC(__PTRDIFF_TYPE__)},
#endif


#ifdef __ATOMIC_SEQ_CST
    /* __ATOMIC_SEQ_CST => "5" */
    {"__ATOMIC_SEQ_CST", STRMAC(__ATOMIC_SEQ_CST)},
#endif


#ifdef __UINT32_TYPE__
    /* __UINT32_TYPE__ => "unsigned int" */
    {"__UINT32_TYPE__", STRMAC(__UINT32_TYPE__)},
#endif


#ifdef __FLT32X_MIN_10_EXP__
    /* __FLT32X_MIN_10_EXP__ => "(-307)" */
    {"__FLT32X_MIN_10_EXP__", STRMAC(__FLT32X_MIN_10_EXP__)},
#endif


#ifdef __UINTPTR_TYPE__
    /* __UINTPTR_TYPE__ => "long unsigned int" */
    {"__UINTPTR_TYPE__", STRMAC(__UINTPTR_TYPE__)},
#endif


#ifdef __DEC64_SUBNORMAL_MIN__
    /* __DEC64_SUBNORMAL_MIN__ => "0.000000000000001E-383DD" */
    {"__DEC64_SUBNORMAL_MIN__", STRMAC(__DEC64_SUBNORMAL_MIN__)},
#endif


#ifdef __DEC128_MANT_DIG__
    /* __DEC128_MANT_DIG__ => "34" */
    {"__DEC128_MANT_DIG__", STRMAC(__DEC128_MANT_DIG__)},
#endif


#ifdef __LDBL_MIN_10_EXP__
    /* __LDBL_MIN_10_EXP__ => "(-4931)" */
    {"__LDBL_MIN_10_EXP__", STRMAC(__LDBL_MIN_10_EXP__)},
#endif


#ifdef __FLT128_EPSILON__
    /* __FLT128_EPSILON__ => "1.92592994438723585305597794258492732e-34F128" */
    {"__FLT128_EPSILON__", STRMAC(__FLT128_EPSILON__)},
#endif


#ifdef __SIZEOF_LONG_LONG__
    /* __SIZEOF_LONG_LONG__ => "8" */
    {"__SIZEOF_LONG_LONG__", STRMAC(__SIZEOF_LONG_LONG__)},
#endif


#ifdef __FLT128_DECIMAL_DIG__
    /* __FLT128_DECIMAL_DIG__ => "36" */
    {"__FLT128_DECIMAL_DIG__", STRMAC(__FLT128_DECIMAL_DIG__)},
#endif


#ifdef __GCC_ATOMIC_LLONG_LOCK_FREE
    /* __GCC_ATOMIC_LLONG_LOCK_FREE => "2" */
    {"__GCC_ATOMIC_LLONG_LOCK_FREE", STRMAC(__GCC_ATOMIC_LLONG_LOCK_FREE)},
#endif


#ifdef __FLT32X_MIN__
    /* __FLT32X_MIN__ => "2.22507385850720138309023271733240406e-308F32x" */
    {"__FLT32X_MIN__", STRMAC(__FLT32X_MIN__)},
#endif


#ifdef __LDBL_DIG__
    /* __LDBL_DIG__ => "18" */
    {"__LDBL_DIG__", STRMAC(__LDBL_DIG__)},
#endif


#ifdef __FLT_DECIMAL_DIG__
    /* __FLT_DECIMAL_DIG__ => "9" */
    {"__FLT_DECIMAL_DIG__", STRMAC(__FLT_DECIMAL_DIG__)},
#endif


#ifdef __UINT_FAST16_MAX__
    /* __UINT_FAST16_MAX__ => "0xffffffffffffffffUL" */
    {"__UINT_FAST16_MAX__", STRMAC(__UINT_FAST16_MAX__)},
#endif


#ifdef __GCC_ATOMIC_SHORT_LOCK_FREE
    /* __GCC_ATOMIC_SHORT_LOCK_FREE => "2" */
    {"__GCC_ATOMIC_SHORT_LOCK_FREE", STRMAC(__GCC_ATOMIC_SHORT_LOCK_FREE)},
#endif


#ifdef __INT_LEAST64_WIDTH__
    /* __INT_LEAST64_WIDTH__ => "64" */
    {"__INT_LEAST64_WIDTH__", STRMAC(__INT_LEAST64_WIDTH__)},
#endif


#ifdef __UINT_FAST8_TYPE__
    /* __UINT_FAST8_TYPE__ => "unsigned char" */
    {"__UINT_FAST8_TYPE__", STRMAC(__UINT_FAST8_TYPE__)},
#endif


#ifdef __ATOMIC_ACQ_REL
    /* __ATOMIC_ACQ_REL => "4" */
    {"__ATOMIC_ACQ_REL", STRMAC(__ATOMIC_ACQ_REL)},
#endif


#ifdef __ATOMIC_RELEASE
    /* __ATOMIC_RELEASE => "3" */
    {"__ATOMIC_RELEASE", STRMAC(__ATOMIC_RELEASE)},
#endif


