/* This file is automatically generated */
#ifndef _H_HOSTINFO_
#define _H_HOSTINFO_
#define BITS_PER_BYTE			8

#define SIZEOF_CHAR			1
#define SIZEOF_SHORT			2
#define SIZEOF_INT			4
#define SIZEOF_LONG			8
#define SIZEOF_FLOAT			4
#define SIZEOF_DOUBLE			8
#define SIZEOF_LONG_DOUBLE		16
#define SIZEOF_ADDRESS			8

#define ALIGNOF_CHAR			1
#define ALIGNOF_SHORT			2
#define ALIGNOF_INT			4
#define ALIGNOF_LONG			8
#define ALIGNOF_FLOAT			4
#define ALIGNOF_DOUBLE			8
#define ALIGNOF_LONG_DOUBLE		16
#define ALIGNOF_ADDRESS			8

#define CHARS_ARE_SIGNED

#define SIZEOF_LONG_LONG		8
#define ALIGNOF_LONG_LONG		8

#define HOST_OS CYGWIN_NT-6.3
#define HAS_MMAP
#endif /* _H_HOSTINFO_ */
