#!/usr/bin/ruby

BADMACROS = /cdecl|attribute/i

begin
  text = %x(gcc "$@" -dM -E - < /dev/null).strip
  File.open("defaultmacros.h", "wb") do |fh|
    fh.printf("/* THIS FILE WAS AUTOMATICALLY GENERATED BY mkmacros.rb! DO NOT EDIT IT DIRECTLY. */\n")
    text.split(/\n/).map(&:strip).each do |ln|
      next if ln.empty?
      ps = ln.match(/^\s*#\s*define\s*(?<word>[\w_]+)\s+(?<value>.*)/)
      next if ps.nil?
      w = ps["word"]
      val = ps["value"].strip
      next if w.match?(BADMACROS)
      $stderr.printf("macro: '%s' => %p\n", w, val)
      fh.printf(
        "#ifdef %<name>s\n" +
        "    /* %<name>s => %<val>p */\n" +
        "    {%<name>p, STRMAC(%<name>s)},\n" +
        "#endif\n\n\n", name: w, val: val)
    end
  end
end